name: Apps Link
'on':
  pull_request:
    branches:
      - master
jobs:
  AppLink:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 2
          github_token: ${{ secrets.HUB_TOKEN }}
      - run: |
          git config --global user.email "devin.gallage@clouda.io"
          git config --global user.name "kulanjith"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Install python pyyaml
        run: pip install pyyaml
      - name: install yaspin
        run: pip install --upgrade yaspin
      - name: install yarn
        run: npm install --global yarn
      - name: yarn cache clean
        run: |
          yarn cache clean
          yarn install --network-concurrency 1
      - name: Install toolbelt
        run: |
          yarn global add vtex
          echo "$(yarn global bin)" >> $GITHUB_PATH
      - uses: vtex/action-toolbelt-login@v1
        with:
          account: cloudab2b
          app-key: ${{ secrets.CLOUDA_B2B_APP_KEY }}
          app-token: ${{ secrets.CLOUDA_B2B_APP_TOKEN }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
      - name: branch name
        run: |
          if ${IS_PR}; then
            BRANCH_NAME="${GITHUB_HEAD_REF}"
          else 
            BRANCH_NAME="${GITHUB_REF##*/}"
          fi
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV        
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed" >> changeList.txt
          done
          python3 main.py

